agentAddress = "/tmp/agent.sock"
cmd = "/bin/cat"
cmdArgs = "/dev/stderr"
certDir = "/tmp"
renewSignal = "SIGHUP"
svidFileName = "svid.pem"
svidKeyFileName = "svid_key.pem"
svidBundleFileName = "svid_bundle.pem"
