

init:
	./drew.sh init

ami:
	./drew.sh packer

launch:
	./drew.sh apply -auto-approve

destroy:
	./drew.sh destroy -force

ssh_server:
	./drew.sh ssh server

ssh_agent:
	./drew.sh ssh agent

show:
	./drew.sh agents


