

init:
	./tf.sh init

ami:
	./tf.sh packer

launch:
	./tf.sh apply -auto-approve

destroy:
	./tf.sh destroy -force

ssh_server:
	./tf.sh ssh server

ssh_agent:
	./tf.sh ssh agent

show:
	./tf.sg agents


